version: '3'

services:
  web:
    build:
      context: nginx
    container_name: web
    ports:
      - 8080:80
    networks:
      - proxy-network
    depends_on:
      - node
  node:
    build:
      context: node
    container_name: node
    volumes:
      - ./node/app:/usr/src/app 
    networks:
      - proxy-network
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: mysql
    container_name: db
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/db:/var/lib/mysql
    restart: always
    tty: true
    networks:
      - proxy-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  proxy-network:
    driver: bridge
