version: '3'

services:
  web:
    build:
      context: nginx
    container_name: web
    ports:
      - 8080:80
    networks:
      - proxy-network
  node:
    build:
      context: node
    container_name: node
    networks:
      - proxy-network
  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - proxy-network

networks:
  proxy-network:
    driver: bridge
