version: '3'

services:
  web:
    build:
      context: nginx
    container_name: web
    ports:
      - 8080:80
    networks:
      - proxy-network
    depends_on:
      - node
  node:
    build:
      context: node
    container_name: node
    networks:
      - proxy-network
    depends_on:
      - db
  db:
    build:
      context: mysql
    container_name: db
    command: --innodb-use-native-aio=0
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/db:/var/lib/mysql
    restart: always
    tty: true
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
